tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
filter:
    excluded_paths:
        - 'spec/*'

checks:
    php:
        avoid_duplicate_types: true
        avoid_tab_indentation: true
        avoid_usage_of_logical_operators: true
        avoid_useless_overridden_methods: true
        blank_line_after_namespace_declaration: true
        classes_in_camel_caps: true
        code_rating: true
        deprecated_code_usage: true
        ensure_lower_case_builtin_functions: true
        fix_identation_4spaces: true
        fix_line_ending: true
        fix_linefeed: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        instanceof_class_exists: true
        lowercase_basic_constants: true
        lowercase_php_keywords: true
        no_else_if_statements: true
        no_eval: true
        no_global_keyword: true
        no_goto: true
        no_space_around_object_operator: true
        no_space_inside_cast_operator: true
        no_unnecessary_if: true
        one_class_per_file: true
        optional_parameters_at_the_end: true
        parameters_in_camelcaps: true
        precedence_in_conditions: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        simplify_boolean_return: true
        single_namespace_per_use: true
        space_after_cast: true
        spacing_around_conditional_operators: true
        spacing_around_non_conditional_operators: true
        too_many_arguments: true
        unreachable_code: true
        unused_methods: true
        unused_parameters: true
        unused_properties: true
        unused_variables: true
        uppercase_constants: true
        use_statement_alias_conflict: true
        verify_access_scope_valid: true
