language: php

php:
    - 5.5
    - 5.6
    - hhvm

before_script:
    - composer self-update
    - composer install --dev --prefer-source --no-interaction

script: vendor/bin/phpspec run

after_script:
  - php vendor/bin/coveralls

matrix:
  allow_failures:
    - php: hhvm
